name: dio_firebase_performance
description: A new Flutter package project.
version: 0.4.0
homepage: https://github.com/eyeem/dio_firebase_performance

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  firebase_performance: ^0.9.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
